name: Run VCP Analyzer

on:
  schedule:
    # Runs at 9:00 AM IST (3:30 AM UTC) every weekday
    - cron: '30 3 * * 1-5'
    # Runs at 3:00 PM IST (9:30 AM UTC) every weekday
    - cron: '30 9 * * 1-5'
  workflow_dispatch:  # Allows manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run VCP Analyzer
      run: |
        python vcp_classic_csv.py --headless

    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add vcp_analysis_results.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update VCP analysis results - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}